### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by Badal-05**
Created License.

# Pull request template

### CODE REVIEW

**Comment by Basilbabyskaria** [comment]
bro the topic itself is very basic try contributing something useful. just google !

**Comment by Badal-05** [comment]
Sorry for my work :(.
I am a newbie and this is my first time in open source contribution.

**Comment by Basilbabyskaria** [comment]
its ok bro. research a bit about vs code in YouTube and pick a topic search it on google you will get plenty on content. even if i accept your work they will check each and every contribution before giving you points. i will accept even if the contribution is small. try bro you can do this.

**Comment by Badal-05** [comment]
Sure I will try.
And thanks alot for the guidance.
Highly appreciated.

**Pull request closed without merging**
